# Generated by Django 4.2.1 on 2023-05-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_learning', '0003_remove_post_creador_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creador',
        ),
    ]
