# Generated by Django 4.2.1 on 2023-05-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0007_alter_curso_duracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
