# Generated by Django 4.2.1 on 2023-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0008_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(default='Descripción pendiente', max_length=150),
        ),
    ]
