# Generated by Django 4.2.1 on 2023-05-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0009_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(default='Descripción pendiente', max_length=800),
        ),
    ]
